services:
  selectzyme-proxy:
    image: ghcr.io/ipb-halle/selectzyme-app/proxy:0.0.5  # from docker.publish-proxy.yml IMAGE_NAME
    # Port forwarding disabled for production runs (profiles or docker-compose.override.yml can be used alternatively)
    # ports:
    #   - "80:80"
    depends_on:
      - selectzyme-demo
      - selectzyme-petase
      - selectzyme-ired
      - selectzyme-lpor
      - selectzyme-lov
      - selectzyme-fmos
    networks:
      - selectzyme-network
      
  selectzyme-demo:
    image: ghcr.io/ipb-halle/selectzyme-app/selectzyme:0.0.5
    environment:
      - DASH_URL_BASE_PATHNAME=/demo/
      - SELECTZYME_DATASET=demo
    networks:
      - selectzyme-network

  selectzyme-petase:
    image: ghcr.io/ipb-halle/selectzyme-app/selectzyme:0.0.5
    environment:
      - DASH_URL_BASE_PATHNAME=/petase/
      - SELECTZYME_DATASET=petase
    networks:
      - selectzyme-network

  selectzyme-ired:
    image: ghcr.io/ipb-halle/selectzyme-app/selectzyme:0.0.5
    environment:
      - DASH_URL_BASE_PATHNAME=/ired/
      - SELECTZYME_DATASET=ired
    networks:
      - selectzyme-network

  selectzyme-lpor:
    image: ghcr.io/ipb-halle/selectzyme-app/selectzyme:0.0.5
    environment:
      - DASH_URL_BASE_PATHNAME=/lpor/
      - SELECTZYME_DATASET=lpor
    networks:
      - selectzyme-network      

  selectzyme-lov:
    image: ghcr.io/ipb-halle/selectzyme-app/selectzyme:0.0.5
    environment:
      - DASH_URL_BASE_PATHNAME=/lov/
      - SELECTZYME_DATASET=lov
    networks:
      - selectzyme-network

  selectzyme-fmos:
    image: ghcr.io/ipb-halle/selectzyme-app/selectzyme:0.0.5
    environment:
      - DASH_URL_BASE_PATHNAME=/fmos/
      - SELECTZYME_DATASET=fmos
    networks:
      - selectzyme-network

networks:
  selectzyme-network:
    driver: bridge
