server {
    listen 80;
    server_name localhost;

    # Serve the static index.html
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Forward to Demo-analysis container
    location /demo/ {
        proxy_pass http://selectzyme-demo:8050/demo/;
    }

    # Forward to PETase container
    location /petase/ {
        proxy_pass http://selectzyme-petase:8050/petase/;
    }

    # Forward to IRED container
    location /ired/ {
        proxy_pass http://selectzyme-ired:8050/ired/;
    }

    # Forward to LPOR container
    location /lpor/ {
        proxy_pass http://selectzyme-lpor:8050/lpor/;
    }

    # Forward to LOV container
    location /lov/ {
        proxy_pass http://selectzyme-lov:8050/lov/;
    }

    # Forward to FMOS container
    location /fmos/ {
        proxy_pass http://selectzyme-fmos:8050/fmos/;
    }
}